README.md
authmate/authmate.go

 Add cid to output of authmate issue-secret

---

api/handler/head.go
api/layer/object.go

[#160] Fix head dir object

---

api/handler/object_list.go
api/handler/response.go
api/layer/object.go

[#159] Add fetch-owner param

---

README.md
api/auth/center.go
api/handler/list.go
api/handler/put.go
api/layer/container.go
api/layer/layer.go
api/user-auth.go
authmate/authmate.go
cmd/authmate/main.go
creds/accessbox/accessbox.go
creds/accessbox/accessbox.pb.go
creds/accessbox/accessbox.proto
creds/tokens/credentials.go

[#89] Add placement policy

---

api/handler/get.go

[#118] Correct NotFound status

---

api/handler/put.go
api/layer/layer.go
api/layer/object.go
api/layer/object_cache.go
api/layer/util.go

ListObjectsV2 cache

---

api/handler/object_list.go
api/handler/object_list_test.go

Add check of continuation token

---

api/errors.go
api/handler/api.go
api/handler/copy.go
api/handler/delete.go
api/handler/get.go
api/handler/head.go
api/handler/info.go
api/handler/list.go
api/handler/not-support.go
api/handler/object_list.go
api/handler/put.go
api/handler/unimplemented.go
api/handler/util.go
api/max-clients.go
api/reqinfo.go
api/response.go
api/user-auth.go

[#184] Unify error handling

---

api/layer/layer.go
api/layer/object.go
api/layer/object_cache.go
api/layer/object_cache_test.go

Add cache to ListObjectsV1

---

README.md
api/errors/errors.go
api/handler/acl.go
api/handler/acl_test.go
api/handler/put.go
api/handler/response.go
api/handler/unimplemented.go
api/headers.go
api/layer/container.go
api/layer/layer.go

[#49] Add acl translation

---

api/handler/put.go

[#214] Add condition to update eacl

---

docs/configuration.md

Replace 'HTTP_' by 'S3'

---

api/handler/head.go
api/headers.go

[#220] Add cid to HeadBucket response

---

api/handler/api.go
api/handler/put.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
docs/configuration.md

[#218] Configurable default policy

---

api/cache/buckets.go
api/errors/errors.go
api/handler/get.go
api/handler/head.go
api/handler/not_support.go
api/handler/put.go
api/handler/response.go
api/handler/tagging.go
api/handler/tagging_test.go
api/handler/unimplemented.go
api/headers.go
api/layer/layer.go
api/layer/object.go
api/layer/util.go
api/layer/versioning.go
docs/aws_s3_compat.md
docs/s3_test_results.md

The following tests pass now:
* s3tests_boto3.functional.test_s3:test_get_obj_tagging 
* s3tests_boto3.functional.test_s3:test_get_obj_head_tagging
* s3tests_boto3.functional.test_s3:test_put_max_tags
* s3tests_boto3.functional.test_s3:test_put_max_kvsize_tags
* s3tests_boto3.functional.test_s3:test_put_excess_key_tags
* s3tests_boto3.functional.test_s3:test_put_excess_val_tags
* s3tests_boto3.functional.test_s3:test_put_delete_tags
* s3tests_boto3.functional.test_s3:test_put_obj_with_tags 
closes #196 

Add bucket tagging

---

api/handler/acl.go
api/handler/acl_test.go
api/handler/put.go
api/handler/response.go

[#213] Add object acl versioning

---

CHANGELOG.md

CHANGELOG: Add latest changes of v0.17.0 release

---

authmate/authmate.go
cmd/authmate/main.go

[#241] Add aws-cli-credentials flag

---

api/handler/delete.go
api/headers.go
api/layer/layer.go
api/layer/versioning.go
api/layer/versioning_test.go
docs/s3_test_results.md

[#248] Support delete marker

---

authmate/authmate.go
cmd/authmate/main.go
creds/tokens/credentials.go

[#255] Add expiration to access box

---

docs/s3_test_results.md
updateTestsResult.sh

[#249] Add update tests result script

---

docs/aws_s3_compat.md

[#266] Update aws s3 compatibility doc

---

api/handler/acl.go
api/handler/delete.go
api/handler/get.go
api/handler/tagging.go
api/handler/versioning.go

[#262] Fix status codes

---

api/layer/layer.go
api/layer/object.go
api/layer/versioning.go
api/layer/versioning_test.go

[#263] Add LWW to system objects

---

.golangci.yml
api/layer/container.go

Replace golint by revive

---

api/data/info.go
api/errors/errors.go
api/handler/api.go
api/handler/cors.go
api/handler/unimplemented.go
api/headers.go
api/layer/cors.go
api/layer/layer.go
api/layer/object.go
api/layer/system_object.go
api/layer/versioning.go
api/router.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
docs/s3_test_results.md

Support CORS

---

api/cache/system.go
api/data/info.go
api/handler/cors.go
api/layer/cors.go
api/layer/layer.go
api/layer/system_object.go
api/layer/versioning.go

[#274] Refactor system cache and cors

---

api/layer/container.go
api/layer/layer.go
api/layer/versioning_test.go
cmd/s3-gw/app.go
go.mod
go.sum

This PR change bucket name resolving mechanism from listing owner's containers to using system DNS. But to test this system DNS must be configured correctly.
Should be considered with https://github.com/nspcc-dev/neofs-dev-env/pull/149
closes #219

[#219] Add container name resolving

---

api/errors/errors.go
api/handler/list.go
api/handler/multipart_upload.go
api/handler/unimplemented.go
api/handler/util.go
api/headers.go
api/layer/layer.go
api/layer/multipart_upload.go
api/layer/multipart_upload_test.go
api/layer/object.go
api/layer/system_object.go
api/layer/versioning.go
api/layer/versioning_test.go
api/router.go
docs/aws_s3_compat.md
docs/s3_test_results.md

Multipart upload

---

cmd/authmate/main.go

[#295] authmate: Fix replace in obtain-secret

---

.github/workflows/tests.yml

[#265] Add go 1.17 to run tests

---

cmd/authmate/main.go

Closes #290 
Added timeout to `issue-secret` and `obtain-secret` commands. Default value is 1 minute, the value can be set with a flag `--timeout 10s/42m/100500h`.
Timeout option is common for both commands and, like `--with-log` and `--debug` must be placed before `issue-secret` and `obtain-secret`.

[#290] Add timeout to authmate

---

api/layer/container.go
authmate/authmate.go

[#299] Fix creating named containers

---

api/data/info.go
api/handler/info.go
api/handler/put.go
api/layer/container.go
api/layer/layer.go
docs/aws_s3_compat.md
docs/s3_test_results.md

[#301] Implement GetBucketLocation

---

docs/s3_test_results.md
updateTestsResult.sh

[#304] Add minio test results

---

api/response.go

[#305] Fix UnknownAPIRequest handling

---

api/layer/layer.go
api/resolver/resolver.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go

[#285] Add resolving order

---

api/handler/get.go
api/layer/layer.go
api/layer/object.go
api/layer/system_object.go
docs/s3_test_results.md

[#307] Filter system metadata

---

api/errors/errors.go
api/handler/acl.go
api/handler/delete.go
api/handler/put.go
api/metrics/api.go
api/metrics/collector.go
api/reqinfo.go
cmd/s3-gw/app_router.go

Closes #316 
Also replaced errs returned by `xml.Decode` with errors with `BadRequest` code.

[#316] Remove MinIO related errors

---

authmate/authmate.go
cmd/authmate/main.go

[#324] Make sure the default container name is unique

---

api/handler/get.go
api/headers.go
api/layer/layer.go
docs/s3_test_results.md

[#310] Override response header

---

api/handler/copy.go
api/handler/list.go
api/handler/multipart_upload.go
api/handler/object_list.go
api/layer/multipart_upload.go

[#331] Use UTC Last-Modified time

---

api/data/info.go
api/handler/object_list.go
api/layer/layer.go
api/layer/object.go
api/layer/versioning.go
api/layer/versioning_test.go
docs/s3_test_results.md

[#319] Fix null versions

---

api/layer/object.go
docs/s3_test_results.md

Closes #313, #314 
Removed extra QueryUnescapes in search and objectPut

[#313] Remove extra QueryUnescapes

---

api/handler/put.go
api/layer/container.go
api/layer/layer.go
authmate/authmate.go
authmate/authmate_test.go
creds/accessbox/accessbox.go
creds/accessbox/accessbox.pb.go
creds/accessbox/accessbox.proto
creds/accessbox/bearer_token_test.go
docs/authmate.md

Update protobuf structs to support multiple session tokens for container operations and use appropriate tokens for PUT, DELETE, SetEACL operations
closes #329

[#329] Multiple container session tokens in auth box

---

authmate/authmate.go
docs/authmate.md

[#336] Update default session token rules

---

authmate/authmate.go
cmd/authmate/main.go
docs/authmate.md

[#338] Remove redundant flag for session tokens in authmate

---

authmate/authmate.go

[#343] Replace default policy in authmate

---

api/layer/layer.go

[#354] Check container owner if bucket exists

---

authmate/authmate.go

[#348] Remove prefix to errors in authmate

---

authmate/authmate.go
docs/authmate.md

Add SETEACL token to authmate

---

api/cache/system.go
api/data/info.go
api/data/notifications.go
api/errors/errors.go
api/handler/not_support.go
api/handler/notifications.go
api/handler/unimplemented.go
api/layer/layer.go
api/layer/notifications.go
api/notifications/controller.go
cmd/s3-gw/app.go

[#340] Notification handlers

---

authmate/authmate.go
cmd/authmate/main.go

[#364] Support placement policy overriding

---

api/layer/container.go

[#366] Add wait for container removed

---

api/layer/layer.go
api/layer/object.go
api/layer/system_object.go

[#368] Unify cache value deletion

---

authmate/authmate.go
cmd/authmate/main.go

[#372] Check parameters before creating container

---

api/handler/acl.go
api/handler/copy.go
api/handler/cors.go
api/handler/delete.go
api/handler/get.go
api/handler/handlers_test.go
api/handler/head.go
api/handler/info.go
api/handler/locking.go
api/handler/locking_test.go
api/handler/multipart_upload.go
api/handler/notifications.go
api/handler/object_list.go
api/handler/put.go
api/handler/tagging.go
api/handler/util.go
api/handler/versioning.go
api/layer/container.go
api/layer/layer.go
api/layer/multipart_upload.go
api/layer/object.go
api/layer/versioning.go
api/layer/versioning_test.go

[#377] Reuse BucketInfo in layer

---

api/layer/layer.go
api/notifications/controller.go
cmd/s3-gw/app.go

[#384] Add check of Notificator interface value in Initialize func

---

authmate/authmate.go
cmd/authmate/main.go

[#387] authmate: fix parsing session rules

---

api/handler/put.go
api/handler/versioning.go
api/layer/system_object.go

[#389] Fix checks of bucket settings

---

api/data/notifications.go
api/handler/copy.go
api/handler/delete.go
api/handler/multipart_upload.go
api/handler/notifications.go
api/handler/put.go
api/layer/layer.go
api/layer/notifications.go
api/layer/notifications_test.go
api/layer/versioning_test.go
api/notifications/controller.go

Closes #357, closes #358, closes #359

[#357] Add basic notifications

---

api/handler/delete.go
api/layer/layer.go

Fixed handlers for failed tests

---

api/handler/acl.go
api/handler/multipart_upload.go
api/handler/put.go

Signed-off-by: Angira Kekteeva <kira@nspcc.ru>

[#395] Fix grantee in ACL

---

api/handler/handlers_test.go
api/layer/container.go
api/layer/layer.go
cmd/authmate/main.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
go.mod
go.sum
internal/neofs/neofs.go

[#365] Update SDK

---

api/handler/multipart_upload.go
api/layer/multipart_upload.go

Moved deletion of parts after putting a final object, acl and tags.
Closes #400

[#400] Fix complete-multipart-upload

---

api/handler/acl.go
api/handler/multipart_upload.go
api/handler/put.go
api/handler/util.go

[#347] Add setEACL session token checks

---

api/handler/delete.go
api/layer/container.go
api/layer/object.go
internal/neofs/neofs.go
internal/neofs/neofs_test.go

[#367] Check errors using statuses

---

docs/authmate.md
docs/configuration.md

Goland processed incorrect links in docs as correct links, but now I detected that links are actually incorrect

Fix links in docs

---

authmate/authmate.go
docs/authmate.md

[#406] authmate: update default bearer rules

---

cmd/authmate/main.go

Signed-off-by: Alex Vanin <alexey@nspcc.ru>

[#409] authmate: Fix container ID parsing

---

authmate/authmate.go

Related to #422
Consider as temporary solution. Need resolution in https://github.com/nspcc-dev/neofs-sdk-go/issues/235.

authmate: Fix extended ACL rules reading

---

internal/neofs/neofs.go

1 second interval drastically improves experience in neofs-dev-env and does not produce much load in production.

internal/neofs: Use custom poll interval

---

api/handler/api.go
api/handler/copy.go
api/handler/delete.go
api/handler/multipart_upload.go
api/handler/notifications.go
api/handler/notifications_test.go
api/handler/put.go
api/layer/layer.go
api/layer/notifications.go
api/notifications/controller.go
cmd/s3-gw/app.go

[#391] Refactor notifications

---

api/errors/errors.go
api/handler/attributes.go
api/layer/multipart_upload.go
api/router.go
docs/aws_s3_compat.md

Closes #430 
Also added an attribute with parts' data to attrs of an object created with `complete-multipart-upload`:
`S3-Completed-Parts`: `1=6291456,2=6291456,3=6291456,...part_number=part_size`

[#432] Add get-object-attributes

---

.github/workflows/builds.yml
.github/workflows/tests.yml
go.mod
go.sum

Update go version to 1.17

---

internal/neofs/neofs.go

Disable homomorphic hash if possible

---

api/layer/layer.go
api/layer/object.go
api/layer/system_object.go
api/layer/tree_service.go
api/layer/versioning.go
api/layer/versioning_test.go
cmd/s3-gw/app.go
go.sum
internal/neofs/tree.go
internal/neofs/tree_signature.go
syncTree.sh

Note this PR will be work after https://github.com/nspcc-dev/neofs-node/pull/1395
close #413, close #414

[#413] Use tree service to handle versions

---

internal/neofs/tree.go

[#444] Handle trailing slash in names

---

api/cache/objectslist.go
api/data/info.go
api/data/tree.go
api/layer/layer.go
api/layer/object.go
api/layer/system_object.go
api/layer/tree_service.go
api/layer/versioning.go
api/layer/versioning_test.go
internal/neofs/tree.go
internal/neofstest/tree/tree_mock.go

[#420] List versions using the tree service

---

api/cache/objects.go
api/data/tree.go
api/handler/multipart_upload.go
api/layer/layer.go
api/layer/multipart_upload.go
api/layer/object.go
api/layer/tree_service.go
internal/neofs/tree.go
internal/neofstest/tree/tree_mock.go

[#417] Create multipart upload using tree service

---

internal/neofs/tree.go

must be merged after #448 
close #453

[#453] Use only FileName as path attribute

---

api/headers.go
api/layer/container.go
cmd/authmate/main.go

Fixes `test_bucket_get_location` from s3-tests.
Closes #468

Define default location constraint

---

api/data/info.go
api/handler/versioning.go
api/layer/system_object.go

```
s3tests_boto3.functional.test_s3.test_multipart_copy_versioned ... ok
s3tests_boto3.functional.test_s3.test_versioning_bucket_create_suspend ... ok
s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_removal ... ok
s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_overwrite ... ok
s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_overwrite_suspended ... ok
```
close #462 

[#462] Fix None versioning status

---

api/cache/system.go
api/data/locking.go
api/data/tree.go
api/handler/delete.go
api/handler/get.go
api/handler/head.go
api/handler/locking.go
api/handler/locking_test.go
api/handler/multipart_upload.go
api/handler/put.go
api/handler/tagging.go
api/layer/cors.go
api/layer/layer.go
api/layer/locking_test.go
api/layer/notifications.go
api/layer/object.go
api/layer/system_object.go
api/layer/tagging.go
api/layer/tree_service.go
api/layer/versioning.go
api/layer/versioning_test.go
internal/neofs/tree.go
internal/neofstest/tree/tree_mock.go

[#451] Handle lock objects using tree service

---

go.mod
go.sum

[#460] Update sdk

---

api/data/tree.go
api/handler/handlers_test.go
api/handler/object_list.go
api/handler/object_list_test.go
api/layer/layer.go
api/layer/object.go
api/layer/tagging.go
api/layer/util.go
api/layer/versioning.go
api/layer/versioning_test.go

[#474] Use appropriate null version during listing

---

api/handler/get.go
api/handler/head.go
api/layer/compound.go
api/layer/layer.go
api/layer/tree_mock.go
api/layer/tree_service.go
internal/neofs/tree.go

Reduce number of tree service requests

---

api/handler/attributes.go
api/handler/get.go
api/handler/handlers_test.go
api/handler/head.go
api/handler/head_test.go
internal/neofstest/neofs_mock.go

[#484] Handle conditional headers

---

api/data/tree.go
api/handler/attributes.go
api/handler/atttributes_test.go
api/headers.go
api/layer/multipart_upload.go

[#476] Save full parts info to multipart object

---

api/layer/layer.go

[#513] Don't remove delete mark object

---

api/handler/handlers_test.go
api/layer/container.go
api/layer/layer.go
api/layer/neofs.go
api/layer/neofs_mock.go
api/layer/object.go
api/layer/system_object.go
api/layer/versioning_test.go
internal/neofs/neofs.go
internal/neofs/neofs_test.go

[#438] Drop layer/neofs package

---

internal/neofs/tree.go

[#503] Handle leading slash in names

---

api/handler/tagging.go
api/layer/compound.go
api/layer/layer.go
api/layer/tagging.go

[#514] Missed version id in tags

---

api/cache/accessbox.go
api/cache/buckets.go
api/cache/cache_test.go
api/cache/names.go
api/cache/objects.go
api/cache/objectslist.go
api/cache/system.go
api/handler/handlers_test.go
api/layer/layer.go
api/layer/versioning_test.go
authmate/authmate.go
cmd/s3-gw/app.go

[#465] Handle cache cast failure

---

api/layer/multipart_upload.go

Closes #508 
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>

Fix nil reference when a part is missing

---

internal/neofs/neofs.go

Fix transform of AcessDenied error

---

internal/neofs/tree.go

related to https://github.com/nspcc-dev/neofs-s3-gw/issues/509#issuecomment-1149851220

[#520] Fix saving two lock types simultaneously

---

authmate/authmate.go
go.mod
go.sum

Revert authmate eACL workaround and update SDK

---

api/handler/delete.go
api/handler/delete_test.go
api/handler/handlers_test.go
api/handler/locking_test.go
api/layer/layer.go
api/layer/tagging.go
api/layer/versioning_test.go

[#532] Fix object removal

---

api/handler/acl.go
api/handler/multipart_upload.go
api/handler/tagging.go

Tagging and ACL put notifications

---

README.md
api/auth/center.go
api/auth/signer/v4/header_rules.go
api/auth/signer/v4/options.go
api/auth/signer/v4/request_context_go1.7.go
api/auth/signer/v4/stream.go
api/auth/signer/v4/uri_path.go
api/auth/signer/v4/v4.go

[#528] Add java sdk client configuration

---

.github/workflows/builds.yml
.github/workflows/tests.yml

[#543] Drop workflow dispatch

---

api/layer/object.go
go.mod
go.sum

[#525] Parallelize listing

---

api/cache/cache_test.go
api/cache/objects.go
api/cache/objects_test.go
api/cache/objectslist.go
api/handler/head_test.go
api/layer/multipart_upload.go
api/layer/object.go

[#547] s3 tests teardown fix

---

README.md
docs/tree_service.md

Tree service docs

---

api/handler/head.go
api/layer/object.go

[#289] Add detect mimetype by extension

---

api/handler/acl.go
api/handler/attributes.go
api/handler/copy.go
api/handler/get.go
api/handler/head.go
api/handler/multipart_upload.go
api/layer/compound.go
api/layer/layer.go
api/layer/object.go
api/layer/versioning_test.go

[#490] Optimize GetObjectTaggingAndLock

---

api/handler/handlers_test.go
api/layer/container.go
api/layer/neofs_mock.go
go.mod
go.sum
internal/neofs/neofs.go

* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/234/

Upgrade NeoFS SDK Go with changed container API

---

api/handler/delete.go
api/handler/delete_test.go
api/handler/handlers_test.go
api/layer/layer.go
api/layer/versioning_test.go

[#542] Fix object removal

---

.gitignore
CONTRIBUTING.md
Makefile

- Add contributing guide
- Clean .cache

Minor cosmetical changes for build process

---

api/handler/acl.go
api/handler/acl_test.go

Do not use user role with public keys in eacl target

---

config/config.yaml

[#565] Use localhost instead of 127.0.0.1

---

internal/neofs/tree.go

Note: merging this changed can lead to missing some data if s3-gw will be used with old trees (from tree service)
close #533 

[#533] Fix typos

---

api/handler/acl.go
api/handler/acl_test.go

Fix acl order

---

api/cache/cache_test.go
api/data/info.go
api/handler/delete.go
api/handler/handlers_test.go
api/handler/locking_test.go
api/handler/multipart_upload.go
api/handler/put.go
api/handler/tagging.go
api/handler/versioning.go
api/layer/layer.go
api/layer/locking_test.go
api/layer/object.go
api/layer/system_object.go
api/layer/versioning_test.go
internal/neofs/tree.go

[#569] Refactor versioning in tree service

---

api/handler/acl.go
api/handler/acl_test.go

Mutual exclusion with #594 
Pros:
* example of using service records
* service records can be easily extended to save AWS ACL rules (e.g. `FULL_CONTROL for allUsers`  etc).
Cons:
* we will have to adopt reverse order parsing https://github.com/nspcc-dev/neofs-s3-gw/pull/586/
close #590 

[#590] Use service records to save resource info

---

internal/neofs/tree.go

related to #601
This PR fix listing objects in versioned bucket:
```shell
$ aws s3api create-bucket --bucket bucket07
$ aws s3api put-bucket-versioning --versioning Status=Enabled --bucket bucket07
$ aws s3api put-object --key obj --bucket bucket07
{
"ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
"VersionId": "FucGZeWo9ZvQ12xwJbn9SeoQLwy89b7UogbbN2dePd8z"
}
$ aws s3api delete-object --key obj --bucket bucket07
{
"DeleteMarker": true,
"VersionId": "3GXjbTCTmErDqjxrDpiMCyRoifcnraj5Jzgr98gpxqex"
}
$ aws s3api list-objects --bucket bucket07
```
Output on current `tree-service`:
```shell
$ aws s3api list-objects --bucket bucket07
{
"Contents": [
{
"Key": "obj",
"LastModified": "2022-07-21T08:24:14+00:00",
"ETag": …
```

[#601] Fix GetLatestVersionsByPrefix

---

api/handler/delete_test.go
api/layer/layer.go
api/layer/neofs_mock.go
api/layer/object.go

[#602] Fix removal non-empty bucket

---

cmd/s3-gw/app.go
cmd/s3-gw/app_healthy.go

[#600] Add health metric

---

api/layer/object.go
api/layer/util.go
api/layer/util_test.go

Process delimiters on the object info cache hit

---

api/headers.go
api/layer/layer.go
api/layer/object.go

[#619] Fix filter of system metadata

---

api/handler/object_list_test.go
api/layer/object.go

Fix test `test_bucket_listv2_both_continuationtoken_startafter`
close #612

[#612] Make listing more robust

---

api/handler/delete.go
api/handler/delete_test.go
api/layer/layer.go

Fix tests:
* `s3tests_boto3.functional.test_s3.test_multi_object_delete`
* `s3tests_boto3.functional.test_s3.test_multi_objectv2_delete`
Also don't suppress error on object removal (except `not found` error)
close #610 

[#610] Fix deleted object removal

---

internal/neofs/tree.go

Related #603 
This fix the listing in the following scenario:
* Create versioned bucket
* Put object `obj`
* Put object `obj` again
* Put object `obj/obj2`
* List objects
Without fix listing output:
```shel
$ aws s3api list-objects --bucket dkirillov4
{
"Contents": [
{
"Key": "obj/obj2",
"LastModified": "2022-07-26T15:23:41+00:00",
"ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
"Size": 0,
"Owner": {
"DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
"ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
}
}
]
}
```
after:
```shell
$ aws s3api list-objects --bucket dkirillov4
{
"Contents": [
{
"Key": "obj",
"LastModified": "2022-07-26T15:40:01+00:00",
"ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
"Size": 0,
"Owner": {
"DisplayName": …
```

[#627] Correct listing object same as directory

---

api/handler/util.go
api/layer/multipart_upload.go
internal/misc/sanitizer.go

Closes #498 
`zap` lib does all the job anyway.
Suppress CWE-117 from CodeQL.

Remove log string sanitizer

---

cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md

[#633] Add config param for pool error threshold

---

cmd/s3-gw/app.go
cmd/s3-gw/app_metrics.go
internal/neofs/neofs.go

Based on and blocked by #626
close #615

[#615] Expose pool metrics

---

README.md
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md

[#607] Wallet config

---

api/auth/signer/v4/v4.go
api/handler/tagging.go
api/layer/tagging.go
cmd/s3-gw/main.go

[#643] Fix tagging cache

---

CHANGELOG.md
api/auth/signer/v4/v4.go
api/cache/cache_test.go
api/cache/objects.go
api/cache/objects_test.go
api/data/info.go
api/data/tree.go
api/handler/acl.go
api/handler/attributes.go
api/handler/copy.go
api/handler/delete_test.go
api/handler/get.go
api/handler/head.go
api/handler/multipart_upload.go
api/handler/object_list.go
api/handler/object_list_test.go
api/handler/put.go
api/layer/layer.go
api/layer/locking_test.go
api/layer/object.go
api/layer/object_test.go
api/layer/tagging.go
api/layer/util.go
api/layer/versioning.go
api/layer/versioning_test.go
internal/neofs/tree.go

[#577] Refactoring of ExtendedObjectInfo

---

Makefile

Signed-off-by: anikeev-yadro <a.anikeev@yadro.com>

[#653] Filter version tags for version calculation

---

CHANGELOG.md
api/handler/api.go
api/handler/cors.go
api/handler/locking.go
api/handler/multipart_upload.go
api/handler/notifications.go
api/handler/put.go
api/layer/cors.go
api/layer/layer.go
api/layer/locking_test.go
api/layer/multipart_upload.go
api/layer/neofs.go
api/layer/notifications.go
api/layer/object.go
api/layer/system_object.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md
go.mod
go.sum
internal/neofs/neofs.go

[#634] Configure SetCopiesNumber in NeoFS requests

---

CHANGELOG.md
api/data/tree.go
api/handler/copy.go
api/handler/multipart_upload.go
api/handler/put.go
api/handler/put_test.go
api/layer/layer.go
api/layer/multipart_upload.go
docs/configuration.md

[#637] Support overriding `set_copies_number` config value

---

.github/workflows/builds.yml
go.sum

[#664] Fix go mod

---

cmd/s3-gw/app_metrics.go

Since pool statistic contains current values rather than delta we should use gauge metric.

[#679] Use gauge instead of counter for metrics

---

api/handler/delete_test.go
api/handler/handlers_test.go
api/layer/neofs.go
api/layer/neofs_mock.go
internal/neofs/neofs.go

[#545] Drop object search

---

api/handler/versioning.go

[#660] Fix panic on invalid versioning status

---

internal/neofs/tree.go

[#671] Fix using nested name in multipart upload

---

api/errors/errors.go
api/handler/copy.go
api/handler/copy_test.go
api/headers.go
api/layer/tree_mock.go

[#666] Support tagging directive for CopyObject

---

api/auth/center.go
api/auth/center_test.go
api/auth/regexp_utils.go
api/handler/copy.go
api/handler/copy_test.go
api/handler/multipart_upload.go
api/router.go

[#672] Fix handling X-Amz-Copy-Source header

---

api/handler/acl.go

Put object acl always add rules to specific version of object.
Get object acl consider READ rights as FULL_CONTROL because WRITE cannot be applied to object
close #676 

[#676] Fix object acl

---

go.mod
go.sum

[#687] Update SDK

---

api/handler/object_list_test.go
api/layer/object.go

[#684] Fix continuation token for directories

---

api/handler/put.go

[#656] Read full body on upload error

---

api/handler/copy.go
api/handler/copy_test.go

[#683] Forbid copy to itself in unversioned bucket

---

CHANGELOG.md
api/auth/center.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md

Access key filter

---

README.md
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md

Add listen domains docs

---

api/data/tree.go
internal/neofs/tree.go
syncTree.sh

Based on and blocked by https://github.com/nspcc-dev/neofs-node/pull/1753
Without this PR s3-gw listing on master branch will not work with neofs-node master branch. 
close #624

[#624] Get full subTree for listing

---

api/layer/layer.go

[#704] Fix nil pointer dereference on decReader

---

api/handler/acl.go
api/handler/acl_test.go
api/layer/neofs_mock.go

This PR doesn't change order of conflicting records for `OTHERS` role
close #606 
```shell
$ aws s3api create-bucket --bucket acl2 
ALLOW GET          [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a} ]
ALLOW HEAD         [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a} ]
ALLOW PUT          [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a} ]
ALLOW DELETE       [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a} ]
ALLOW SEARCH       [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a} ]
ALLOW GETRANGE     [ ] [ ROLE_UNSPECIFIED:{031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c …
```

[#606] Keep eacl records order on conflict

---

api/handler/handlers_test.go
api/layer/layer.go
api/resolver/resolver.go
cmd/s3-gw/app.go
cmd/s3-gw/app_metrics.go
cmd/s3-gw/app_settings.go
cmd/s3-gw/main.go

Blocked by https://github.com/nspcc-dev/neofs-http-gw/pull/201
Add reload on SIGHUP:
* config level
* certs
* resolvers
* metrics
close #702

[#702] Reload config level on SIGHUP

---

cmd/s3-gw/app.go

[#716] Fix start TLS server

---

docs/configuration.md

[#715] SIGHUP reload doc

---

api/cache/cache_test.go
api/cache/objectslist.go
api/cache/objectslist_test.go

[#650] Drop unused object cache methods

---

docs/aws_cli.md

docs: Clarify some outputs of bucket creation

---

CHANGELOG.md
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md
go.mod
go.sum

[#750] Update SDK to support timeout for stream

---

api/layer/object.go

[#741] Fix data race

---

CHANGELOG.md
api/handler/api.go
api/handler/attributes.go
api/handler/copy.go
api/handler/encryption_test.go
api/handler/get.go
api/handler/handlers_test.go
api/handler/head.go
api/handler/multipart_upload.go
api/handler/put.go
api/router.go
cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
cmd/s3-gw/server.go
config/config.env
config/config.yaml
docs/configuration.md

[#742] Add multiple listeners

---

cmd/s3-gw/app.go
go.mod
go.sum

Signed-off-by: Denis Kirillov <d.kirillov@yadro.com>

[#767] Update neofs SDK

---

api/handler/acl.go
api/handler/acl_test.go
api/handler/put.go
api/handler/response.go
api/handler/response_test.go

Also fix `AccessControlPolicy` XML.

acl: Make some code refactoring

---

CHANGELOG.md
cmd/s3-gw/app.go
go.mod
go.sum

Port changes from v0.26.1 release

---

api/layer/container.go
api/layer/object.go
go.mod
go.sum
internal/neofs/neofs.go

Update sdk to rc.9

---

.docker/Dockerfile

close #788 
#786 Should be merged first

Simplify docker image

---

.github/workflows/dco.yml

workflow: use DCO check from .github

---

api/handler/acl.go
api/handler/acl_test.go

Don't add eACL rules to System group

---

.github/workflows/system-tests.yml

workflow: fix repo path

---

.docker/Dockerfile
.github/workflows/builds.yml
.github/workflows/s3-tests.yml
.github/workflows/system-tests.yml
.github/workflows/tests.yml
Makefile
go.mod
go.sum

Upgrade to go 119

---

CHANGELOG.md
api/handler/util.go
api/layer/neofs.go
api/layer/object.go
docs/aws_s3_compat.md

PutObject metadata with empty string

---

docs/aws_s3_compat.md

Update docs about ETag

---

docs/aws_s3_compat.md
go.mod
go.sum

Use SDK with pool base multi sessions

---

.github/workflows/system-tests.yml

workflows: Fix checkout neofs-s3-gw repository

---

cmd/s3-authmate/main.go

Restrict presigned URL lifetime

---

api/handler/not_support.go
api/router.go

Return unsupported error on GetObjectTorrent

---

api/handler/not_support.go
api/router.go

Return unsupported error on PutPublicAccessBlock

---

api/auth/center.go
api/auth/center_test.go

During #882 fix, I lost one place to change
Closes #850.

Return the correct error, if x-amz-credential is not provided

---

api/handler/not_support.go
api/router.go

Not implemented err on GetPublicAccessBlock

---

.github/workflows/s3-tests.yml
.github/workflows/system-tests.yml

github: use older dev-env for tests

---

.github/workflows/s3-tests.yml
.github/workflows/system-tests.yml

Added usage of gh-push-to-neofs action to test workflows

---

api/handler/unimplemented.go
api/router.go

Closes #907.
GetBucketLogging already marked as not implemented

PutBucketLogging is not implemented

---

.github/CODEOWNERS

auto-requested review from maintainers as a bonus

github: Actualize CODEOWNERS

---

authmate/authmate.go
docs/authmate.md

Rid of no-op record

---

api/handler/cors.go
api/router.go

Process Options before auth

---

.golangci.yml
creds/accessbox/accessbox.go

951 potentially insecure hkdf use

---

api/handler/acl.go
api/handler/util.go
api/layer/neofs.go

These changes should fix [the test](https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/313-1724132371/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/aaf43750a90cc668/)

Change http 500 to 400 for user.ID decode

---

docs/aws_s3_compat.md

Clarify LocationConstraint parameter

---

docs/aws_s3_compat.md

Extend docs limitations for PutObjectAcl

---

docs/aws_s3_compat.md

docs: Add missed bucket method

---

api/layer/multipart_upload.go
api/s3errors/errors.go

Return error if previous part is missing

---

api/data/tree.go
api/layer/multipart_upload.go
api/layer/neofs.go
api/layer/tree_mock.go
internal/neofs/neofs.go
internal/neofs/tree.go

Parallel uploads for multipart

---

api/metrics/collector.go

Make metrics names consistent

---

api/handler/acl.go
api/handler/copy.go
api/handler/multipart_upload.go
api/handler/put.go
docs/aws_s3_compat.md

Enable all ACLs with BucketOwnerPreferred without policies

---

CHANGELOG.md
api/auth/center.go

Disable uri path escaping for presigned URLs

---

.github/workflows/s3-tests.yml

closes https://github.com/nspcc-dev/s3-tests/issues/79

.github: set correct status for failed test reports

---

.github/workflows/s3-tests.yml

closes https://github.com/nspcc-dev/s3-tests/issues/80

.github: hardcode aws cli version

---

cmd/s3-gw/service.go

Refs #1045.
More info required to understand what is happening.

Log error on shutdown

---

api/handler/tagging.go
api/layer/layer.go
api/layer/tagging.go
api/layer/tree_mock.go
api/layer/tree_service.go
api/s3headers/headers.go
internal/neofs/tree.go

Remove tree-service usage for bucket tags

---

.github/workflows/system-tests.yml

.github: run neofs-testcases tests in parallel

---

api/layer/notifications.go
api/layer/object.go
api/layer/tagging.go
api/layer/tree_mock.go
api/layer/tree_service.go
api/s3headers/headers.go
internal/neofs/tree.go

Remove tree-service usage for bucket notifications config

---

api/layer/cors.go
api/layer/system_object.go
api/layer/tree_mock.go
api/layer/tree_service.go
api/s3headers/headers.go
internal/neofs/tree.go

Remove tree-service usage for bucket CORS config

---

CHANGELOG.md
cmd/s3-gw/app_settings.go
config/config.env
config/config.yaml
docs/configuration.md

Update logger config

---

cmd/s3-gw/app.go
cmd/s3-gw/app_settings.go
config/config.yaml
docs/configuration.md
internal/neofs/neofs.go

Set experimental __NEOFS__METAINFO_CONSISTENCY container attribute

---

api/handler/object_list.go
api/handler/response.go

Return prefix for ListObjectVersions request

---

internal/neofs/neofs.go

Disable homomorphic hashing for container

---

README.md

Update minimalistic gateway setup

---

api/layer/layer.go

Search refactorings

---

api/layer/layer.go
api/layer/object.go
api/layer/system_object.go

Optimize tags and lock search.

---

api/layer/layer.go
api/layer/object.go

Remove metafiles when deleting object

---

api/layer/layer.go
api/layer/object.go
api/layer/system_object.go
api/layer/tagging.go
api/s3headers/headers.go
docs/attribute_mapping.md

Drop metatypelock

---

api/layer/multipart_upload.go
api/layer/neofs_mock.go
api/layer/object.go

Remove old object versions in unversioned container

---

.github/workflows/s3-tests.yml

.git: drop explicit versions from test workflow config

---

CHANGELOG.md
README.md
cmd/s3-gw/app.go
cmd/s3-gw/app_metrics.go

Update health metric

---

api/layer/multipart_upload.go

Write attribute if not empty

---

api/handler/ownership.go
api/layer/detector.go
authmate/authmate.go
authmate/session_tokens.go
cmd/s3-gw/app_metrics.go
cmd/s3-gw/app_settings.go
creds/accessbox/accessbox.go
creds/tokens/credentials.go

According to https://github.com/nspcc-dev/.github/pull/42.

Fix linter errors
