api/handler/get.go, api/handler/get_test.go
The following tests now pass:
* s3tests_boto3.functional.test_s3.test_ranged_request_invalid_range 
* s3tests_boto3.functional.test_s3.test_ranged_request_empty_object 
* s3tests_boto3.functional.test_s3.test_ranged_request_response_code 
* s3tests_boto3.functional.test_s3.test_ranged_big_request_response_code 
* s3tests_boto3.functional.test_s3.test_ranged_request_skip_leading_bytes_response_code 
* s3tests_boto3.functional.test_s3.test_ranged_request_return_trailing_bytes_response_code 
closes #194 
=> [#194] Fix range header handling

api/handler/get.go, api/handler/put.go
The following test now pass: 
* s3tests_boto3.functional.test_s3:test_object_set_get_metadata_none_to_good
closes #198 
=> [#198] Fix object metadata

api/handler/copy.go, api/handler/put.go, api/headers.go
The following tests now pass:
* s3tests_boto3.functional.test_s3:test_object_copy_verify_contenttype 
* s3tests_boto3.functional.test_s3:test_object_copy_to_itself 
* s3tests_boto3.functional.test_s3:test_object_copy_retaining_metadata 
* s3tests_boto3.functional.test_s3:test_object_copy_replacing_metadata 
* s3tests_boto3.functional.test_s3:test_object_copy_bucket_not_found 
* s3tests_boto3.functional.test_s3:test_object_copy_key_not_found
closes #191 
=> [#191] Improve copy object compatibility

api/cache/bucket.go, api/cache/buckets.go, api/cache/head_cache.go, api/cache/names.go, api/cache/object_cache.go, api/cache/object_cache_test.go, api/cache/system.go, api/errors/errors.go, api/handler/acl.go, api/handler/copy.go, api/handler/delete.go, api/handler/get.go, api/handler/head.go, api/handler/list.go, api/handler/not_support.go, api/handler/object_list.go, api/handler/put.go, api/handler/response.go, api/handler/versioning.go, api/headers.go, api/layer/container.go, api/layer/detector.go, api/layer/layer.go, api/layer/object.go, api/layer/object_list_cache.go, api/layer/util.go, api/layer/util_test.go, api/layer/versioning.go, api/layer/versioning_test.go, docs/aws_s3_compat.md
The following tests pass now:
* s3tests_boto3.functional.test_s3:test_versioning_bucket_create_suspend 
* s3tests_boto3.functional.test_s3:test_atomic_read_1mb 
* s3tests_boto3.functional.test_s3:test_atomic_read_4mb 
* s3tests_boto3.functional.test_s3:test_atomic_read_8mb 
* s3tests_boto3.functional.test_s3:test_atomic_write_1mb 
* s3tests_boto3.functional.test_s3:test_atomic_write_4mb 
* s3tests_boto3.functional.test_s3:test_atomic_write_8mb
* s3tests_boto3.functional.test_s3:test_bucket_delete_notexist 
* s3tests_boto3.functional.test_s3:test_bucket_delete_nonempty 
* s3tests_boto3.functional.test_headers:test_object_create_bad_expect_empty 
* s3tests_boto3.functional.test_headers:test_object_create_bad_expect_none 
* s3tests_boto3.functional.test_headers:test_object_create_bad_contentt …
=> [#122] Add enabling versioning

api/auth/center.go, api/auth/center_test.go, api/handler/put.go, api/handler/put_test.go, api/handler/response.go, api/handler/unimplemented.go, api/router.go
To upload file using a form (with authenticated request) first we need make `policy` with some restriction. After than we encode policy using base64 and sign it. Then we have to create html form with  some fields (all fields (except `x-amz-signature`, and some others) in the form also must be in the policy). Among these fields must be `policy` and `x-amx-signature` using that s3-gw can verify request.
Aws example https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html
closes #190 
=> [#190] Add POST object

api/handler/put.go, api/layer/object.go, api/layer/versioning.go, api/layer/versioning_test.go, docs/s3_test_results.md
Test `s3tests_boto3.functional.test_s3:test_versioned_object_acl` test still fails but the reason is different: the notary absent  and  acl user `grant` format inconsistency.
closes #242 
=> [#242] Fix versions sorting

cmd/authmate/main.go
Lifetime cannot be parsed using time unit greater than an hour (e.g. `1d2h30m`) because of golang `time.Duration` limitations.
So this PR updates description of the `lifetime` parameter.
closes #282 
=> [#282] Fix lifetime examples

CHANGELOG.md
Skipped:
#274 -- internal change, can be considered as a part of cors
#278 -- a part of cors
#282 -- fix of #258 which was added in this release
#287, #186 -- minor changes
Mentioned to #276 instead of #271 because the task changed and the PR gives more information than the issue.
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>
=> CHANGELOG: Add latest changes of v0.18.0 release

api/handler/multipart_upload.go, docs/s3_test_results.md
Support `X-Amz-Version-Id` in `CompleteMultipartUpload` method
closes #318 
=> [#318] Support x-amz-version-id in CompleteMultipartUpload

api/handler/put.go, api/handler/put_test.go
Add handling empty post policy
If this PR will be merged after https://github.com/nspcc-dev/neofs-sdk-go/pull/122 (and sdk version will be updated in s3-gw) we can update test results for:
* `test_s3.test_post_object_anonymous_request`
* `test_s3.test_post_object_set_success_code`
closes #306 
=> [#306] Handle empty post policy

api/layer/layer.go, api/layer/object.go, api/layer/system_object.go, docs/s3_test_results.md
As I understand currently we cannot know type of neofs error so in this PR `strings.Contais(...)` is used.
This works on neofs-nodes that have [this fix](https://github.com/nspcc-dev/neofs-node/issues/1098)
Test `test_s3.test_100_continue` now has problem with bucket ACL (new rules are appended to the end of eACL table so they have no effect because above them there are denial rules)
closes #308
=> [#308] Correct status code

api/handler/get.go, api/handler/put.go, docs/s3_test_results.md
Support header `Expires` and `Cache-Control`. They don't affect s3-gw action but we now can save it as neofs attributes
closes #312
=> [#312] Support cache control headers

api/layer/object.go, api/layer/system_object.go
Fix using bearer token for put system objects. This bug was the reason for not being able to enable bucket versioning.
=> [#399] Use bearer token for system objects

api/layer/object.go, api/layer/util.go, api/layer/util_test.go
ETag is a string with SHA256 of NeoFS object payload. Hash is taken from object header by neofs-sdk-go getter. Checksum type in neofs-sdk-go has changes `String()` output from `<hash>` to `SHA256:<hash>` in latest update.
S3 gateway should not be relied on unstable string format implementations and use raw value.
Before:
```
{                                                                              
"ETag": "SHA256:11388ba8886676b0c3fc39e9b944e3533d5c5d14d76d715d8053bad1d73071d2"                                                                          
}
```
After:
```
{
"ETag": "11388ba8886676b0c3fc39e9b944e3533d5c5d14d76d715d8053bad1d73071d2"
}
```
=> Fix ETag value

api/layer/system_object.go
There is a small optimization for object put upload stream into bucket with empty settings. We do not cache empty bucket settings, therefore it produces cache miss and extra search request every time. In `tree-service` it will be extra RPC to the tree service, which is better than whole search.
The downside is that we a are going to store some empty structs in the cache.
In my local test, object stream upload in such bucket became ~10% faster. I expect to see less improvement in `tree-service`.
We can discuss is it worth to use this optimization for such a corner case.
```
Before:
iterations.............: 1527  24.29636/s
After:
iterations.............: 1705  27.391307/s
```
Test suit
```js
import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';
import s3 from …
```
=> Less cache misses for empty bucket setting

api/layer/object.go, api/layer/object_test.go
Related to #441 
Hash can be calculated locally in S3 gateway. Creation epoch used for versioning and will be fetched during get and list requests. To avoid conflicts, put method do not update cache anymore.
=> Do not produce object.Head request at regular object upload

api/cache/objectslist.go, api/handler/handlers_test.go, api/layer/object.go, api/layer/tree_service.go, internal/neofs/tree.go, internal/neofstest/tree/tree_mock.go
closes #416
The basic list tests are passed:
```
s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_alt ... ok
s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_alt ... ok
s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_prefix_underscore ... ok
s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix_underscore ... ok
s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_percentage ... ok
s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_basic ... ok
s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_basic ... ok
s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_prefix ... ok
s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix ... ok
s3tests_boto3.functional.test_s3.test_bucket_list_empty …
```
=> [#416] Use tree service to list objects

api/handler/acl.go
Triggered by `s3tests_boto3.functional.test_s3.test_bucket_policy_set_condition_operator_end_with_IfExists`
=> Do not pass nil error to `logAndSendError`

api/handler/notifications.go, api/layer/layer.go, authmate/authmate.go, creds/accessbox/bearer_token_test.go, go.mod, go.sum
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/259
I don't insist on merging this PR, just opened it for information and advice.
=> Upgrade SDK with latest `bearer` package API

api/handler/copy.go, api/handler/get.go, api/handler/head.go, api/handler/multipart_upload.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/object.go, api/layer/system_object.go, api/layer/versioning_test.go
The `test_object_copy_canned_acl` test still not passing because `main_wallet` creates a private container in tests and `alt_wallet` can't `get-object` from private container, even the object was put with `public-read` acl. 
I tried to make `main-wallet` create `public-read` container and the test began to pass.   
I suggest to fix the test and place it in `test_s3_neofs.py`. 
Closes #459
=>  Remove attach of bearer token when bucket owner is not an issuer of the bearer token  

internal/neofs/tree.go
related to #501 
Fixes:
* s3tests_boto3.functional.test_s3:test_bucket_list_long_name
* s3tests_boto3.functional.test_s3:test_bucket_list_distinct
* s3tests_boto3.functional.test_s3:test_bucket_list_empty
=> [#502] Fix list empty bucket

api/handler/api.go, api/handler/put.go, api/layer/container.go, api/layer/layer.go, authmate/authmate.go, cmd/s3-gw/app.go, creds/accessbox/accessbox.go, go.mod, go.sum, internal/neofs/neofs.go
`PlacementPolicy` type now provides methods to work with QL-encoded
policies. System network parameters can be read using dedicated method
without iterating. Applications can work with `PlacementPolicy`
variables directly so there is no need to use pointers.
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/271
=> Upgrade NeoFS SDK Go with changed `netmap` package

api/handler/acl.go, api/handler/copy.go, api/handler/delete.go, api/handler/put.go, api/layer/container.go, api/layer/layer.go, api/layer/neofs.go, api/layer/neofs_mock.go, go.mod, go.sum, internal/neofs/neofs.go
After recent changes in NeoFS SDK Go library session tokens aren't
embedded into `container.Container` and `eacl.Table` structures.
Instead, the operations of storing given values in NeoFS are
parameterized by elements of the corresponding type.
Add dedicated session parameters to operations of bucket and eACL
setting.
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/276
=> Upgrade NeoFS SDK Go with another approach of container sessions

api/layer/neofs.go, go.mod, go.sum, internal/neofs/neofs.go
SDK now provides dedicated type for basic ACL with convenient interface.
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/272
=> Upgrade NeoFS SDK Go with changed basic ACL API

api/auth/center.go, api/cache/objects_test.go, api/cache/objectslist_test.go, api/handler/acl.go, api/handler/attributes.go, api/handler/cors.go, api/handler/delete.go, api/handler/multipart_upload.go, api/handler/notifications.go, api/handler/put.go, api/handler/response.go, api/layer/container.go, api/layer/cors.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/notifications.go, api/layer/object.go, api/layer/system_object.go, api/notifications/controller.go, api/resolver/resolver.go, api/response.go, authmate/authmate.go, authmate/session_tokens.go, cmd/authmate/main.go, creds/accessbox/accessbox.go, creds/tokens/credentials.go, internal/neofs/neofs.go, internal/wallet/wallet.go
Didn't add context to some error because such errors can already be [appropriate error](https://github.com/nspcc-dev/neofs-s3-gw/blob/8a1fc8ae3f99cff5dc060d969a384e94e109ec1f/api/errors/errors.go#L15) and we have to preserve this.
I see two possible approach to manage this (add context to all errors): 
1. Add the following function and Invoke it [here](https://github.com/nspcc-dev/neofs-s3-gw/blob/8a1fc8ae3f99cff5dc060d969a384e94e109ec1f/api/response.go#L116) (to send appropriate error to user):
```
func fetchS3Error(err error) *errors.Error {
for err != nil {
if e, ok := err.(errors.Error); ok {
return &e
}
err = stderrors.Unwrap(err)
}
return nil
}
```
2. Add the following function and invoke it when we want to add context:
```
func wrapError(err error, msg string) error {
if _, ok := …
```
=> [#539] Add context to errors

go.mod, go.sum
Now policy parser doesn't print failures into stdout but returns the
first one in `error` value.
* closes #557
=> Upgrade NeoFS SDK Go with fixed policy parser

go.mod, go.sum, internal/neofs/neofs.go
Use `pool.SyncContainerWithNetwork` function to correctly compose new
container in `neofs.NeoFS.CreateContainer`.
=> Upgrade NeoFS SDK Go to v1.0.0-rc.5

cmd/s3-authmate/main.go
I'm not sure is there a convenient way to differentiate invalid plain-string json and non-existing filepath, that's why `authmate` returns the same error for both cases. But text of the error when file cannot be read become clearer.
Closes #558
=>  Fix error when file with policy cannot be read

cmd/s3-authmate/main.go, cmd/s3-gw/app_settings.go
Output:
```
$ neofs-s3-gw --version
NeoFS S3 Gateway
Version: v0.21.1-72-gb43a4194
GoVersion: go1.17.3
$ neofs-s3-authmate --version
NeoFS S3 Authmate
Version: v0.21.1-72-gb43a4194
GoVersion: go1.17.3
```
close #578
=> [#578] Unify version output

api/handler/acl.go, api/handler/acl_test.go
Closes #574 
Now private objects produce DENY eACL actions as expected.
=> [#574] Produce deny records for private objects

internal/neofs/neofs.go
Closes #540 
In public containers sticky bit allows to limit
ownership of the objects by request authors.
In private or public-read containers it doesn't
make any sense so sticky bit is redundant there.
=> Do not set sticky bit in authmate container

docs/s3_test_results.md
Most of failed tests are broken because of https://github.com/nspcc-dev/neofs-node/issues/1628
After that we should look at lock tests: https://github.com/nspcc-dev/neofs-s3-gw/issues/639
Also this PR updates counters for non s3-gw columns.
=> Update compatibility table

CHANGELOG.md, internal/neofs/tree.go
There is two approaches: 
1. Move existing version node and remove old tagging in subtree of new node
2. Remove old version node and put new version node
I prefer the first rather than the second because correct replace of node is more important and one request (move) leads to less chance to fail. 
Closes #645
=> [#645] Replace tagging when PutObject

api/handler/delete_test.go, api/handler/object_list_test.go, api/layer/object.go, api/layer/util.go, api/layer/util_test.go
This PR:
* limit generator with `max-keys` value to avoid get extra objects
* if object couldn't be `HEAD` from NeoFS we form it using `data.NodeVersion` (it doesn't have some fields: `createdAt`, `owner` but the `name`, `size` and `etag` are still valid)
* check if object is directory before request to NeoFS
Close #625, close #616
=> Optimize listing

api/layer/layer.go, api/layer/object.go, api/layer/tree_mock.go, api/layer/tree_service.go, internal/neofs/tree.go
Close #682 
This PR updates tree service interface to return added node id in `AddVersion` method. 
---
```
Done with cleanup of buckets in tests.
Done with cleanup of buckets in tests.
Done with cleanup of buckets in tests.
s3tests_boto3.functional.test_s3.test_get_obj_head_tagging ... ok
```
=> Fix object head after put

api/layer/object.go, api/layer/system_object.go, api/layer/tagging.go
This is a part of #669.
In this PR, `PutLockInfo` takes optional argument of tree service node. If this argument is provided, then `PutLockInfo` produces one less network call. It is useful for object upload.
=> Optimize PutLockInfo

.github/workflows/tests.yml
We should definitely have tests running on the version of `go` from go.mod.
=> [#705] Return go1.17 to CI tests

api/handler/util.go, api/layer/multipart_upload.go, api/response.go, api/router.go
Closes #728 
Now it prints:
```
2022-10-25T19:12:46.858+0400    e call method     {"status": 404, "request_id": "9d453cba-eeff-4814-ab59-8e95bb5a3665", "method": "HeadObject", "bucket": "test", "object": "c", "description": "could not find object", "error": "NoSuchKey: 404 => The specified key does not exist."}
2022-10-25T19:16:44.016+0400    error   api/user_auth.go:30     failed to pass authentication   {"error": "get box: get access box: read payload: init full payload range reading via connection pool: read header: status: code = 2049 message = object not found"}
2022-10-25T19:13:35.055+0400     call method     {"status": 500, "request_id": "a2bf1363-2f15-4615-b33e-acce27ac5768", "method": "PutObject", "bucket": "test", "object": "b", "description": "could not upload object", "error": …
```
=> [#729] Add error message to AbortMultipartUpload

CHANGELOG.md, api/layer/container.go
User system name (`__NEOFS__NAME`) instead of regular one (`Name`). We shouldn't show user container name from regular attribute because the user cannot use it as bucket name when do request to s3-gw.
Set name as CID if name attribute is missed
close #733 
=> [#733] Fix container name

CHANGELOG.md, api/auth/center.go, api/handler/api.go, api/handler/copy.go, api/handler/locking.go, api/handler/locking_test.go, api/handler/notifications.go, api/handler/put.go, api/layer/container.go, api/layer/cors.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/neofs.go, api/layer/neofs_mock.go, api/layer/notifications.go, api/layer/object.go, api/layer/system_object.go, api/notifications/controller.go, api/user_auth.go, internal/neofs/neofs.go
Use `X-Amz-Date` header as `now` when
* compute expiration epoch
* set Timestamp for object and container
* forming locks
* send notifications
close #726 
=> [#726] Use client time on regular requests

api/handler/multipart_upload.go, api/handler/put.go, api/handler/tagging.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/object.go, api/layer/tagging.go
Signed-off-by: Artem Tataurov <a.tataurov@yadro.com>
Close/Closes #754
Most handlers have the logging call on first levels.
Some of them rely on logging calls placed deeper at `getNodeVersion` and `getNodeVersionFromCache`: this is for cases when OID is not available for higher levels. Examples:
* DeleteObjectHandler
* DeleteMultipleObjectsHandler
* AbortMultipartUploadHandler
* PutObjectRetentionHandler
* GetObjectRetentionHandler
* PutObjectLegalHoldHandler
* GetObjectLegalHoldHandler
* ListMultipartUploadsHandler
* ListPartsHandler
=> [#754] Add CID and OID to logs

api/handler/multipart_upload.go, api/handler/put.go, api/handler/tagging.go, api/layer/multipart_upload.go
Closes #754 
Removed logging from ListParts at `layer/multipart_upload.go` since more detailed logging happens in `getUploadParts` that gets called in ListParts.
Signed-off-by: Artem Tataurov <a.tataurov@yadro.com>
=> [#754] Remove logging from ListParts

internal/neofs/neofs.go
It's always nil here and it's OK because there is a key in the pool. Broken by 64a38a4ac7b1f5e74c538583c5df0c51cfb61c79.
=> neofs: don't panic on missing signer key for request, fix #784

api/layer/container.go, api/layer/neofs_mock.go, go.mod, go.sum, internal/neofs/neofs.go
It's fixed in nspcc-dev/neofs-sdk-go#440, but we use the same workaround as the REST gw here for RC9.
=> update SDK to RC9+ to fix DeleteObject bug

api/handler/versioning.go
Status "0" is obviously wrong here:
2023-06-14T16:52:41.092Z        info    api/router.go:162       call method     {"status": 0, "host": "s3.neofs.devenv:8080", "request_id": "30aa2d82-5cca-4c9c-9b24-41450d708990", "method": "PutBucketVersioning", "bucket": "08ba13ed-3d5d-45c0-a4b7-8a544b016ec5", "object": "", "description": ""}
Related to #791.
=> handler: return 200 from PutBucketVersioning

.docker/Dockerfile
closes #814 
Changing to _Alpine_ version is required to install `jq` package. But this alpine image doesn't contain some important packages, thus installed them too.
Using jq also required because it formats JSON from Github request and we _grep_ results from it
=> Fix image build

internal/neofs/neofs.go
=> Write object payload if exists

.github/test-env, .github/workflows/s3-tests.yml
Merge after
https://github.com/nspcc-dev/s3-tests/pull/34
https://github.com/nspcc-dev/s3-tests/pull/33
- Workflow runs 250 sanity tests on PR and full test suite on any other event. 
- Sanity run takes less than 30 minutes. 
- For now, for Sanity I picked a set of tests, that are always green during my test runs
- Full test suite runs around 5 hours.
After merging we'll need to add action secrets:
secrets.TEST_RESULTS_WALLET
secrets.TEST_RESULTS_PASSWORD
And action variables:
vars.TEST_RESULTS_NEOFS_NETWORK_DOMAIN
vars.TEST_RESULTS_CID
vars.TEST_RESULTS_HTTP_GATE
SSL is going to be fixed on later stages
=> Workflow to run S3 tests. Fixes #782

.github/test-env
Node and IR versions bumped to 0.38.1 for S3-tests dev-env
=> Update test-env bump node and IR versions

.github/testcases-env, .github/workflows/system-tests.yml
Merge after neofs-testcases fix is merged:
https://github.com/nspcc-dev/neofs-testcases/pull/644
An example of a successfull test run could be found in my fork: 
https://github.com/MaxGelbakhiani/neofs-s3-gw/actions/runs/6256899655/job/16988422370
=> Neofs testcases workflow. Fixes #782

cmd/s3-authmate/main.go, cmd/s3-gw/app.go, cmd/s3-gw/app_settings.go, config/config.env, config/config.yaml, internal/neofs/epoch.go, internal/neofs/neofs.go
=> Add slicer as an option

.github/workflows/s3-tests.yml
Added missing step "Get the current date".
Without this step, the RUN_ID variable had an invalid value in it. For example:
"RUN_ID: 34-"
=> workflows: Add missing step

.github/workflows/s3-tests.yml
In order to support https://github.com/nspcc-dev/s3-tests/pull/43. There is just one set of tests, it runs for 8min30sec, there is no point of having two different sets of tests right now.
=> .github: update s3 tests run step

api/handler/acl.go, api/handler/acl_test.go, api/handler/response.go
=> Public read acl results in full control permission

docs/aws_s3_compat.md
We explicitly mention GW doesn't support this group. Because in NeoFS only two groups: owner and others. Right now there is no possible way to determine who is who.
Closes #858.
=> Extend docs about Authenticated Users group

api/handler/acl.go, api/handler/util.go
=> Handle bad user id more gracefully

api/auth/center.go, api/auth/signer/v4/v4.go, api/user_auth.go
=> Not accurate error message for invalid authenticated requests

api/handler/not_support.go, api/router.go
=> Return unsupported error on GetBucketPolicyStatus

api/handler/locking_test.go, api/layer/system_object.go, docs/aws_s3_compat.md
Lock object can't be deleted with Delete call, https://github.com/nspcc-dev/neofs-api/blob/1424834f743842b88e02ec6ac79c64ef2d2d3e75/lock/types.proto#L13.
Closes #868.
=> Return not supported error for PutObjectLegalHold command if OFF state

api/auth/center.go, cmd/s3-authmate/main.go, internal/limits/const.go
Fixing authmate wasn't enough.
Closes #853.
=> Check x-amz-expires header on maximum border

api/handler/locking.go, api/handler/locking_test.go
=> Return correct error on lock configuration check

Makefile
=> Remove 'v' from app version

api/layer/tagging.go
=> Return error if no tags in bucket

.github/workflows/tests.yml, api/data/tree.go, api/layer/multipart_upload.go, cmd/s3-authmate/main.go, go.mod, internal/neofs/tree.go
Closes #901.
During my first review, I didn't make two fields sort, only one - this was an error point.
Runed
```
S3TEST_CONF=s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_multipart_resend --disable-warnings
```
Before changes
```
80 failed, 70 passed in 408.67s (0:06:48)
```
After changes
```
150 passed in 402.04s (0:06:42)
```
=> Sort parts by number and server creation time

go.mod, internal/neofs/tree_signature.go
=> neofs/tree: don't use neofs-crypto directly

api/data/tree.go, api/handler/acl.go, api/handler/handlers_test.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/neofs.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/tree_mock.go, api/layer/tree_service.go, api/layer/versioning_test.go, go.mod, go.sum, internal/neofs/neofs.go, internal/neofs/tree.go
=> Remove re-slicing for multipart

syncTree.sh
i tried to fix for #940, and saw a request for a fix within #939 late. We can handle this before or just cherry-pick there, up to you @roman-khimov @smallhive 
in the future, i'd try to switch to using some stable GitHub API ([trees](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28) or [contents](https://docs.github.com/en/rest/repos/contents))
=> Makefile: Fix `sync-tree`

api/handler/acl.go, authmate/session_tokens.go, authmate/session_tokens_test.go, go.mod, go.sum, internal/neofs/neofs_test.go
it's going to be deprecated. Any app should use https://github.com/nspcc-dev/neofs-sdk-go only
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/570
=> Do not use `github.com/nspcc-dev/neofs-api-go/v2 module` directly

api/handler/acl.go, api/handler/acl_test.go, api/handler/json_types.go, api/handler/json_types_test.go, docs/aws_s3_compat.md
The PR is not solving test issues completely. It gives the ability to use wildcards in `Principal` and `Action` fields
=> Update ACL structures to have flexible types

go.mod, go.sum
=> go.mod: update NeoGo dependency to 0.106.2

api/layer/layer.go
=> Remove actual object version

api/cache/objects_test.go, api/handler/acl.go, api/handler/acl_test.go, api/handler/multipart_upload.go, api/handler/object_list.go, api/handler/put.go, api/handler/response_test.go, api/layer/versioning_test.go, go.mod, go.sum
Refs https://github.com/nspcc-dev/neofs-api/issues/278
The changes require test changes as well.
ACL owner will be changed from
```json
{
"Owner": {
"DisplayName": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM",
"ID": "033845e8ebc78251029261cbc0e9bae104d2b7cc9fee5c79720a30332d5b3d1aa0"
},
"Grants": [
{
"Grantee": {
"DisplayName": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM",
"ID": "033845e8ebc78251029261cbc0e9bae104d2b7cc9fee5c79720a30332d5b3d1aa0",
"Type": "CanonicalUser"
},
"Permission": "FULL_CONTROL"
}
]
}
```
to
```json
{
"Owner": {
"DisplayName": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM",
"ID": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM"
},
"Grants": [
{
"Grantee": {
"DisplayName": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM",
"ID": "Nj9FF9jYTsyX2XniTw5Kqy3Zf91nbhdYiM",
"Type": "CanonicalUser"
},
"Permission": …
```
=> Accounts in eacl

api/handler/acl.go, api/handler/multipart_upload.go, api/handler/put.go
@smallhive, that's what I'm expecting when we change something like this. It was specifically designed to simplify things, so it should simplify things.
=> api: drop useless key->issuer transformations

api/layer/layer.go, docs/aws_s3_compat.md
=> Document X-Amz-Meta-Neofs-Copies-Number header

api/layer/layer.go
=> layer: Return error if object locked

api/layer/object.go, internal/neofs/neofs.go, internal/neofs/neofs_test.go
I've put the versioning bucket settings check in a separate commit. Do we really want to have this _nonce_ only for the versioning bucket? I consider it possible to have this situation in a regular container as well.
Thus we may merge this commit with the first one or just drop
Closes #986
=> Same versionid for different versions

api/layer/multipart_upload.go, internal/neofs/neofs.go
=> Excessive memory consumption in slicing code

CHANGELOG.md, config/config.env, config/config.yaml, docs/configuration.md
Closes #973.
Node timeout left as is, 10s. According to the [REST gate](https://github.com/nspcc-dev/neofs-rest-gw/pull/244/files#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bbaR22)
=> Update default timeout

api/layer/multipart_upload.go, api/layer/neofs.go, api/layer/object.go, internal/neofs/neofs.go
=> Sign multipart objects in the gate

api/auth/center.go, api/handler/put.go, api/handler/util.go
=>  Use chunked reader if content market with STREAMING-AWS4-HMAC-SHA256-PAYLOAD header

.golangci.yml, api/handler/encryption_test.go
We can't reuse the job at the moment because of the tree service code (#1007), but let's at least grab the best settings we can have now (they don't change often anyway).
=> golangci: update configuration from org-wide linter

.github/workflows/builds.yml
It's deprecated and soon to be removed.
https://github.com/actions/runner-images/issues/10721
=> workflows: replace macos-12 with macos-14

CHANGELOG.md, cmd/s3-gw/app_settings.go
Skipping log lines is not safe to be used by default. Notice that s3-authmate doesn't have this problem because of the way it constructs its settings.
See also:
* https://github.com/nspcc-dev/neofs-node/pull/3011
* https://github.com/nspcc-dev/neo-go/pull/598
=> cmd: disable zap log sampling

cmd/s3-authmate/main.go
=> Check endpoint validity for pre-signed URLs

api/layer/multipart_upload.go, go.mod, internal/neofs/tree.go
Ref https://github.com/nspcc-dev/neofs-testcases/pull/906
=> Fix multipart

api/layer/multipart_upload.go, api/layer/neofs.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/system_object.go, internal/neofs/neofs.go
=> Deduplicate object attributes

api/handler/acl.go, api/handler/acl_test.go, api/handler/copy.go, api/handler/multipart_upload.go, api/handler/ownership.go, api/handler/put.go, authmate/authmate.go, cmd/s3-authmate/main.go, internal/neofs/neofs.go
=> Fix eacl issue in copyobject

CHANGELOG.md, api/handler/lifecycle.go, api/handler/unimplemented.go, docs/aws_s3_compat.md
=> Add partial support for GetBucketLifecycle operation

api/handler/delete_test.go, api/handler/get.go, api/handler/locking.go, api/layer/compound.go, api/layer/layer.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/system_object.go, api/layer/tree_mock.go, api/layer/tree_service.go, api/layer/versioning.go, go.mod, go.sum, internal/neofs/tree.go
=> *: Remove tree service for object operations

api/data/info.go, api/handler/copy.go, api/handler/locking.go, api/handler/object_list.go, api/handler/object_list_test.go, api/handler/tagging.go, api/layer/compound.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/neofs.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/system_object.go, api/layer/tagging.go, api/layer/util.go, api/layer/versioning_test.go, go.mod, go.sum, internal/neofs/neofs.go
=> Integrate search v2

api/auth/center.go, api/cache/objects_test.go, api/cache/objectslist.go, api/data/info.go, api/handler/acl.go, api/handler/acl_test.go, api/handler/ownership.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/util.go, api/layer/versioning_test.go, authmate/authmate.go, creds/tokens/credentials.go, internal/neofs/neofs.go, internal/neofs/neofs_test.go, internal/neofs/tree.go
im exploring how [migration](https://github.com/nspcc-dev/neofs-api/issues/305) to N3 accounts gonna affect S3 gw. Some crypto-related SDK elements will be deprecated. Suddenly discovered that earlier places were not removed, so decided to fix them
=> Avoid deprecated code and refactor IDs

api/data/info.go, api/data/locking.go, api/handler/acl.go, api/handler/multipart_upload.go, api/handler/notifications.go, api/handler/put.go, api/handler/response.go, api/handler/response_test.go
Gitlab doesn't send this field and AWS docs doesn't say the field is mandatory.
Closes #1074.
=> Remove XMLName field for CompleteMultipartUpload

cmd/s3-gw/app.go
Refs #1079.
It enables neofs_s3_gw_state_health metric.
=> Enable metrics properly

api/handler/attributes.go, api/handler/get.go, api/headers.go, api/layer/layer.go, api/layer/multipart_upload.go, api/layer/neofs_mock.go, api/layer/object.go, api/layer/system_object.go, api/layer/tagging.go, api/layer/util.go, api/s3headers/headers.go, docs/attribute_mapping.md, internal/neofs/neofs.go, internal/neofs/neofs_test.go
=> Document objectattribute mapping

api/layer/object.go
=> Duplicates in object listing

CHANGELOG.md, api/data/info.go, api/handler/acl.go, api/handler/acl_test.go, api/handler/copy.go, api/handler/multipart_upload.go, api/handler/ownership.go, api/handler/put.go, cmd/s3-authmate/main.go
=> Move bucket ownership to bucket settings metaobject

api/data/info.go, api/layer/system_object.go, api/s3headers/headers.go
=> Add versioning for the bucket settings meta file

api/s3headers/headers.go, docs/attribute_mapping.md
=> Unify attribute naming

api/handler/api.go, api/handler/put.go, api/layer/layer.go, api/layer/neofs.go, api/layer/neofs_mock.go, cmd/s3-gw/app.go, cmd/s3-gw/storage_policy.go, cmd/s3-gw/storage_policy_provider.go, internal/neofs/neofs.go
=> Get metadata consistency policy from contract

CHANGELOG.md, config/config.env, config/config.yaml, docs/configuration.md
=> Simplify peers config

api/layer/system_object.go, api/s3headers/headers.go, docs/attribute_mapping.md
=> Store lock meta in single attribute

api/handler/get.go, api/handler/put.go, api/handler/tagging.go, api/layer/layer.go, api/layer/object.go, api/layer/tagging.go, api/s3headers/headers.go
Closes #1153.
It would help to make tag based searches in the future.
=> Store object tags as attributes along with a payload

api/layer/multipart_upload.go, api/layer/neofs_mock.go, api/layer/object.go, cmd/s3-gw/app.go, go.mod, go.sum, internal/neofs/neofs.go, internal/neofs/neofs_test.go
=> Fix slicer owner issue

api/handler/object_list.go, api/layer/object.go, api/layer/versioning.go, docs/aws_s3_compat.md
Closes #1175
The tests themselves need to be updated as well
=> s3 pagination failures

api/layer/object.go, api/layer/system_object.go, api/layer/tagging.go, api/s3headers/headers.go, docs/attribute_mapping.md
Locks don't need it since 205357df2c7b002e8a1195b6cdea7527f4859584, now tags can also reus __NEOFS__ASSOCIATE.
=> layer: drop S3-ObjectVersion, fix #1188

CHANGELOG.md, internal/neofs/neofs.go
Similar to https://github.com/nspcc-dev/neofs-rest-gw/pull/313. See https://github.com/nspcc-dev/neofs-api/pull/331.
=> neofs: EpochDuration is seconds since API 2.18

api/handler/locking.go
It is used to properly utilization of object.AttributeAssociatedObject attribute.
It is an accompaniment for https://github.com/nspcc-dev/neofs-testcases/pull/1123
=> Store object version for each lock object

.github/workflows/s3-tests.yml
Use proper latest versions, current s3-tests requires 0.48.0+
=> s3-tests: upgrade NeoFS and NeoGo

CHANGELOG.md, api/layer/layer.go
This only makes pool go wild with error counts/health checks.
=> layer: don't try to delete subsequent objects if context expired
